---
name: Term-TermKey
version: 0.02
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: 'perl wrapper around C<libtermkey>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::PkgConfig: 0
build_requires:
  ExtUtils::PkgConfig: 0
  Module::Build: 0
  Module::Build::Compat: 0
provides:
  Term::TermKey:
    file: lib/Term/TermKey.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
